// Prints which acceptance scenarios named in specs/features/*/tasks.md have a test, and writes specs/coverage.md.
// Usage: npm run spec:coverage [-- --check]   (--check fails when any scenario is missing a test)
import fs from "node:fs";
import path from "node:path";
import { acceptanceCoverage } from "../lib/specs/check";

const root = process.cwd();
const rows = acceptanceCoverage(root);
const total = rows.reduce((sum, row) => sum + row.cited.length, 0);
const covered = rows.reduce((sum, row) => sum + row.covered.length, 0);

const lines = [
  "# Acceptance coverage",
  "",
  "Generated by `npm run spec:coverage`. Do not edit by hand. A scenario counts as covered when its id appears in a file under `lib/` or `e2e/` whose name ends in `.test.ts` or `.spec.ts`. Scenarios of superseded requirements are not counted.",
  "",
  `${covered} of ${total} scenarios have a test.`,
  "",
  "| Feature | Covered | Cited | Missing |",
  "| --- | --- | --- | --- |",
  ...rows.map((row) => `| ${row.feature} | ${row.covered.length} | ${row.cited.length} | ${row.missing.length} |`),
  "",
  "## Missing",
  "",
  ...rows.filter((row) => row.missing.length).flatMap((row) => [`### ${row.feature}`, "", row.missing.map((id) => `\`${id}\``).join(", "), ""]),
];
fs.writeFileSync(path.join(root, "specs", "coverage.md"), lines.join("\n"));

for (const row of rows) console.log(`${row.feature.padEnd(28)} ${String(row.covered.length).padStart(4)} / ${row.cited.length}`);
console.log(`\n${covered} of ${total} scenarios have a test. Wrote specs/coverage.md.`);
if (process.argv.includes("--check") && covered < total) process.exit(1);
